### ISSUE TITLE
Wrong script for systemd startup

### ISSUE THREAD

**Issue by fmalfatto** [darold/sendmailanalyzer#18]
I'm not able to stop sendmailanalyzer via 
"systemctl stop sendmailanalyzer.service" 
under opensuse 12.3.

The service definition has the following line:
ExecStop=/bin/kill -TERM sendmailanalyzer

But kill needs the process id, not the process name.

I tried to change that line to
ExecStop=/bin/kill -TERM $MAINPID
as from systemd docs, but it does not work.

That bug make me unable to have senmailanalyze restarted after syslog rotation, and it fails every night.

**Comment by fmalfatto** [comment]
Small correction:
the reported line in sendmailanalyzer.service
ExecStop=/bin/kill -TERM  `cat /var/run/sendmailanalyzer.pid`
does not work in OpenSuse 13.1, reporting "No such process" .

The correct line would be:
ExecStop=/bin/bash -c "/bin/kill -TERM `/usr/bin/cat /var/run/sendmailanalyzer.pid`"

**Comment by darold** [comment]
Thanks for the report, latest commit be3083f adds your patch.

Best regards,
