### ISSUE TITLE
Not all spam identified using spamd

### ISSUE THREAD

**Issue by sirydog81** [darold/sendmailanalyzer#25]
It seems not all mails are recognized as spam even though in maillog spamd logs them ok.
I have 9 messages as spam but sendmailanalyzer shows only 4.

I can provide the maillog.

Thank you for you very usefull tool!

**Comment by darold** [comment]
This number is not a random number, this is the offset/postition of the last line parse in the log file. It is used to go directly to that position instead or rereading the begining of the log file.

Regards,
