### ISSUE TITLE
Amavis log not read

### ISSUE THREAD

**Issue by sergiodadi** [darold/sendmailanalyzer#26]
Hello,

it seems that my (standard) log for amavis (in mail.log) is not recongnized. The log is:

Feb 13 11:02:43 mx-1 amavis[5136]: (05136-09) Passed CLEAN, [194.167.55.26] [193.54.112.219] <ossecm@monitor> -> <xxx.yyyy@mines-paristech.fr>,<zzzzzzzz@sssssss.mines-paristech.fr>, mail_id: 0gehnk-A5kVd, Hits: -, size: 1332, queued_as: B60132CB20, 152 ms

and noting appears in GUI under amavis menu or spamassasin menu.

I have:
AMAVIS_NAME     amavis|maiad
SPAM_TOOLS      spamassassin,amavis

Versions:
Sendmailanalyzer 9.0
Ubuntu 12.04.5 LTS
 amavisd-new  1:2.6.5-0ubuntu3.2
 MTA is postfix 2.9.6-1~12.04.2

Is it a configuration problem ?

thanks for your help

Serge

**Comment by darold** [comment]
Hi Serge,

Line that passed clean are not parsed by sendmailanalyzer. Do you have lines with Passed/Blocked SPAM/INFECTED? If so please paste some of those line here.

Regards,

**Comment by sergiodadi** [comment]
Hi Darold

thank for the explanation.  I have :

Feb 10 01:27:49 mx-1 amavis[27693]: (27693-06) Blocked INFECTED (Win.Trojan.Generickd-2094), [194.214.158.196] [167.88.35.187] <blombacke@olivesverige.se> -> <xxxxxi@mail.sophia.mines-paristech.fr>, quarantine: 3/virus-3tsxby3v3tSL, Message-ID: <201502100027.t1A0Rldx012631@paris.ensmp.fr>, mail_id: 3tsxby3v3tSL, Hits: -, size: 253117, 284 ms

and it appear in the GUI in virus.

I think everything is ok and the log lines with amavis are well  recognized !

Thanks for your program and your help :-)

Serge

**Comment by darold** [comment]
Ok, thanks for the feedback.
