### ISSUE TITLE
Missing directory for debian packaging

### ISSUE THREAD

**Issue by nqb** [darold/sendmailanalyzer#28]
Hello,
I follow `packaging/README` doc for a Debian install. When I run `dpkg -i sendmailanalyzer_9.1-1_all.deb` in sendmailanalyzer source directory, I get the following errors :
```
Selecting previously unselected package sendmailanalyzer.
(Reading database ... 50483 files and directories currently installed.)
Unpacking sendmailanalyzer (from sendmailanalyzer_9.1-1_all.deb) ...
Setting up sendmailanalyzer (9.1-1) ...
[....] Starting Sendmail Analyzer: sendmailanalyzerFATAL: Output directory /usr/lib/sendmailanalyzer should exists !
 failed!
invoke-rc.d: initscript sendmailanalyzer, action "start" failed.
dpkg: error processing sendmailanalyzer (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for man-db ...
Errors were encountered while processing:
 sendmailanalyzer
```
Creating `/usr/lib/sendmailanalyzer` fixes issue.
In `sendmailanalyzer/debian/sendmailanalyzer/usr`, I don't see a `lib` directory.

**Comment by darold** [comment]
Hi,

Thanks for the report, commit 0a09246 solves this issue,  /usr/lib/sendmailanalyzer is replaced by /var/lib/sendmailanalyzer

Best regards,

**Comment by nqb** [comment]
It works !
