### ISSUE TITLE
how to print postfix mail server logs on html page of my server

### ISSUE THREAD

**Issue by vivek779** [darold/sendmailanalyzer#31]
hi  I am new here installed your sendmailanalyser 
cant figure it out how to print postfix logs on to my local html pages 
please guide how would i do it i am not bale to figure out

**Comment by darold** [comment]
HI,

SendmailAnalyzer do not embed an http server, you need to configure your HTTP server (probably an Apache server) following the recommendation given in the documentation and at end of install.

Regards,
