### ISSUE TITLE
No Records SA and Amavis

### ISSUE THREAD

**Issue by talkinggoat** [darold/sendmailanalyzer#32]
This is a great piece of software, thanks for writing it. 

I am getting an issue where the SpamAssassin and Amavis show 'No record for this period' I have not changed anything from the default settings, including AMAVIS_NAME

Log File Example:
Nov  5 12:04:24 destroyer amavis[1282]: (01282-01) S68df6LqJbl7 FWD from <***@***.com> -> <***@***.com>, BODY=7BIT 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 925141A1A9B

Nov  5 12:04:24 destroyer amavis[1282]: (01282-01) Passed, <***@***.com> -> <***@***.com>, quarantine S68df6LqJbl7, Message-ID: <100216.142193907.201511051804145510819.1144933885@***.com>,

What am I not doing right?
Ubuntu 14.04 SpamAssassin 3.4 postfix 2.11

Thank you.

**Comment by darold** [comment]
Hi,

Can you send me a log file to check what's new in these log to my private mail < gilles AT darold DOT net > if you need privacy. Amavis used to log with (Passed|Blocked) INFECTED which is not the case here.

Best regards,
