### ISSUE TITLE
Clarifying the charts?

### ISSUE THREAD

**Issue by gilgongo** [darold/sendmailanalyzer#35]
Hi - SA is great but I'm finding the charts pretty tricky to read. Would it be possible to fix them so I can see what I'm looking at?

(BTW I can't tell from the pie chart below what the largest slice actually represents)

![chart](https://cloud.githubusercontent.com/assets/4561747/11609154/c3fcfe60-9b76-11e5-8172-17fb9cf4f49a.png)

**Comment by darold** [comment]
Hi,

Thanks for the report, I'm globally agree with your remarks. I will look to enhance these kind of graphs when updating/changing the javascript chart library.

Best regards,

**Comment by darold** [comment]
Commit d3fb6b5 change pie graphs for top sender and recipient relays into bar graphs. Sorry for the delay I just realized that this could be done easily using HTML+CSS and we don't have to wait a graph library change.
