### ISSUE TITLE
Log Format

### ISSUE THREAD

**Issue by kpal38** [darold/sendmailanalyzer#37]
Hello,

What's log format use for sendmailanalyzer ?

I use postfix default format but sendmailanalyzer don't find sender and recipient...

I use this log format:

Sep 15 20:05:24 smtp postfix/qmgr[1350]: 10963200D7: from=<root@toto.fr>, size=2579, nrcpt=1 (queue active)
Sep 15 20:05:24 smtp postfix/local[2245]: 10963200D7: to=<dsi@toto.fr>, orig_to=<root>, relay=local, delay=0.05, delays=0.03/0.01/0/0.01, dsn=5.1.1, status=bounced (unknown user: "dsi")
Sep 15 20:05:24 smtp postfix/cleanup[2240]: 1AD602018D: message-id=<20150915180524.1AD602018D@smtp.fr>

Thank you for response,

Best regards,

**Comment by darold** [comment]
Hi,

This is the right format, you don't have to change anything. This is a bug, last commit c02bf95 might solves the issue, please download latest development code from github and give it a try.

Best regards,

**Comment by kpal38** [comment]
Thank you it works. But I have an another problem:

For october 2015:

In "Messaging flows" I have 1 698 434 incomming messages (it's ok for me) and 853 outgoing message (it's weird...)

In "Message delivery flows" I have:  0 messages "External -> Internal" ; 0 messages "External -> External"  ; 0 messages "Internal -> Internal" and 853 messages "Internal -> External",  this it's weird too...

**Comment by darold** [comment]
Please send me a log file to my private email at gilles@darold.net , I can not help without that.
