### ISSUE TITLE
Spanish locale is wrong

### ISSUE THREAD

**Issue by jguardon** [darold/sendmailanalyzer#39]
Spanish locale must be **es_ES**, not sp_SP, which doesn't exist. Perhaps this doesn't affect the normal behavior of the scripts, but it's good having the stuff sorted ;-)
Regards

**Comment by darold** [comment]
Thanks for the report. Last commit 982ba3f rename the file.

Best regards,

**Comment by jguardon** [comment]
Oh, thanks! Really fast answer. Best regards.
