### ISSUE TITLE
Troubles understanding Message delivery flows

### ISSUE THREAD

**Issue by enekux** [darold/sendmailanalyzer#41]
Hi,

I have troubles understanding the Message delivery flows.

Our Postfix server is used as a "Gateway/AntiSpam-AntiVirus Filter" mail server for multiple domains for Incoming and Outgoing mail flows.

But I don't quite understand the statistics shown under Messaging/Message delivery flows:

External -> Internal
External -> External
Internal -> Internal
Internal -> External

I have been playing with next directives to make some sense, but still I don't understand the results:

LOCAL_DOMAIN domain.com, domain2.com
MAIL_HUB 127.0.0.1,::1,mail.domain.com, mail.domain2.com
MAIL_GW

Would this be ok?

What is the interpretation for:

External -> External
Internal -> Internal

Thank you and regards

**Comment by darold** [comment]
Hi,

Sorry for the response delay. Here you only need to set the list of your internal domain in the  LOCAL_DOMAIN configuration directive. MAIL_HUB and MAIL_GW must be empty.

Regards,

**Comment by enekux** [comment]
Hi,

ok I will give it a try, do some tests and let you know.

Meantime, could you explain which emails fall in the Mail Flows:

External -> External
Internal -> Internal

Thanks

**Comment by darold** [comment]
You might not have External -> External flow, this can result of backscatting or bounced messages. Internal -> Internal is when your MTA is used from and to legit users. To simplify you can see External as Internet and Internal as your private network.

**Comment by romale** [comment]
I've also configured LOCAL_DOMAIN but External->Internal is 0 0.00 0.00%.
Thanks

**Comment by darold** [comment]
Please send me a sample of your log to my private address gilles AT darold DOT net I will try to find the right settings or fix the issue.
