### ISSUE TITLE
SA Report Top Sender only 100?

### ISSUE THREAD

**Issue by stigmatcell** [darold/sendmailanalyzer#43]
Hi,

I want to ask it is possible to append the log grep for top sender where the default is 100? we want to grep the today sender top sender at the gui report in this link http://domain.net/sareport/sa_report.cgi?host=smtp-1&date=20170113&hour=&type=sender&peri=address&domain=&search=user%40domain.net

Thanks and regards,

**Comment by darold** [comment]
Hi,

You just have to increase the value of the MAX_LINE configuration directive.

Regards,

**Comment by stigmatcell** [comment]
Hi,

Thanks for the response. 

I check at file sa_report.cgi but there is no value for MAX_LINE? where i must change the value or i just need change the MAX_LINE into a number? is it correct the file is sa_report.cgi ?
and after we change the value should i run command /usr/local/sendmailanalyzer/sendmailanalyzer -f ?

regards,

**Comment by darold** [comment]
Please have a look to /usr/local/sendmailanalyzer/sendmailanalyzer.conf , this is where your configuration exists.

**Comment by stigmatcell** [comment]
Hi Darold,

Thaks for the solutions. It works for me now.. :)
