### ISSUE TITLE
Recipient from same domain not grep

### ISSUE THREAD

**Issue by stigmatcell** [darold/sendmailanalyzer#44]
Hi Darold,

Sorry if i ask again, in my testing area when i see from top sender detail the recipients with same domain not grep at all but with different domain it appear like google, yahoo, hotmail,etc

it is my topology : 

haproxy (25) > smtp1/smtp2 > recipient

So i have haproxy to load balance the blast email to smtp1 or smtp2. When i check the /var/log/mail.log on both server the recipient is show.

Thanks

**Comment by darold** [comment]
Hi,

I do not understand the problem. Can you send to my private email < gilles AT darold DOT net > a tarball of the data files, for example:
    tar cjf sa_issue_44.tar.bz2 /usr/local/sendmailanalyzer/data/*/2017/01/19/
Regards,

**Comment by stigmatcell** [comment]
Hi darold,

Thanks for the response, i send the mail today

regards
