### ISSUE TITLE
Cannot see UI page

### ISSUE THREAD

**Issue by kennoosh** [darold/sendmailanalyzer#47]
Hi I installed the sendmailanalyzer following the instruction, but when I open the page: https://xx.xx.xx.xx/sareport/;  it doesn't give me any UI page, it only show all perl scripts; please review the attached file; do you know why is that?

[sareport.txt](https://github.com/darold/sendmailanalyzer/files/1015210/sareport.txt)

Thanks

**Comment by kennoosh** [comment]
the OS is ubuntu 14; perl is v5.22.1, and I have installed " MIME::Base64"

**Comment by darold** [comment]
The problem is not related to the perl script but to your Apache configuration. See INSTALLATION in the documentation (README file) and especially the "Post install" chapter and the configuration sample:
```
            Alias /sareport /usr/local/sendmailanalyzer/www
            <Directory /usr/local/sendmailanalyzer/www>
                    Options ExecCGI
                    AddHandler cgi-script .cgi
                    DirectoryIndex sa_report.cgi
                    Order deny,allow
                    Deny from all
                    Allow from 127.0.0.1
                    Allow from ::1
                    # Allow from .example.com
            </Directory>
```

**Comment by kennoosh** [comment]
I added that setting in the apache, but I got 403 forbidden issue:
            Alias /sareport /usr/local/sendmailanalyzer/www 
                <Directory /usr/local/sendmailanalyzer/www>
                    Options ExecCGI
                    AddHandler cgi-script .cgi
                    DirectoryIndex sa_report.cgi
                    Order deny,allow 
                    Allow from all 
                    # Allow from .example.com
                </Directory> 
I googled it and someone suggested to use "Require all granted" instead of "Order deny,allow"; so I changed it as:  
               Alias /sareport /usr/local/sendmailanalyzer/www 
                <Directory /usr/local/sendmailanalyzer/www>
                    Options ExecCGI
                    AddHandler cgi-script .cgi
                    DirectoryIndex sa_report.cgi
                    Require all granted   
                    # Allow from .example.com
                </Directory>

The I can access it but the response is not UI page, it just show all perl scripts;

**Comment by darold** [comment]
What is your version of Apache httpd server (output of `apache2 -v` ) and the version of your operating system?

**Comment by darold** [comment]
Sorry, I just seen your note above: OS is ubuntu 14, I have the same on my laptop and my configuration is:
```
        Alias /sareport /usr/local/sendmailanalyzer/www/
        <Directory /usr/local/sendmailanalyzer/www/>
            Options All +ExecCGI
            Require all granted
            AddHandler cgi-script .cgi
            DirectoryIndex sa_report.cgi
        </Directory>
```
into /etc/apache2/sites-enabled/000-default.conf default virtual host.

**Comment by kennoosh** [comment]
Does it work for you ?  my apache version is 2.4, and I added it in /etc/apache2/sites-enabled/default-ssl.conf because we disabled the HTTP request; all http request will automatically be rewritten to HTTPS;

**Comment by darold** [comment]
Yes it works great for me, perhaps you have to enable the cgi module too.
```
sudo a2enmod cgi
sudo service apache2 reload
```

**Comment by kennoosh** [comment]
yeah, it works, thank you very much
