### ISSUE TITLE
Spec file language updates

### ISSUE THREAD

**Issue by lloydsystems** [darold/sendmailanalyzer#50]
I downloaded the current master code and built a RPM package on CentOS using the spec file provided. Initial build attempt failed with an error about sp_SP in the %files section. Looking at the files, I see that language sp_SP has been renamed to es_ES. I also see languages it_IT and ru_RU are there, but not included in the spec file. Therefore, I think the spec file %files section should be updated with:
--del--  %attr(0644,root,root) %{webdir}/lang/sp_SP
+add+  %attr(0644,root,root) %{webdir}/lang/es_ES
+add+  %attr(0644,root,root) %{webdir}/lang/it_IT
+add+  %attr(0644,root,root) %{webdir}/lang/ru_RU

Regards,
Steve Jones

**Comment by darold** [comment]
Applied in commit d596f6d
