### ISSUE TITLE
Spamming Flows

### ISSUE THREAD

**Issue by cantlep** [darold/sendmailanalyzer#52]
Similar to issue [https://github.com/darold/sendmailanalyzer/issues/51](url) The Spamming flows are a bit off.

![spam_flows](https://user-images.githubusercontent.com/3270673/30453705-a74d0920-9991-11e7-9df5-1199edb43772.png)

It would seem local incoming should correspond with External -> Internal, but  as you can see, that is still showing 0

Also, the outgoing section in the spamming flows suggest 435 email sent from my relay were classed as SPAM. This figure is definitely incorrect. I doubt my system would flag anything it sent as SPAM.

The Incoming Spamming flows suggests a figure of 1328, which when I view the Top statistics -> Spamming section does correspond with the "top spammers"

![top_spammers](https://user-images.githubusercontent.com/3270673/30453827-1c1131e6-9992-11e7-8c6b-25551be6d5e6.png)

However, I cannot find any evidence of any outgoing SPAM. So not sure where the figure of 435 outgoing has come from.

Cheers

**Comment by darold** [comment]
The Top Spam statistics issue is now fixed by commit cf30e95. SA was wrongly reporting as DNSBL Spam blocked all message that had status 550 5.7.1 even if they was not related to RBL.

The Internal vs External flow still needed to be fixed.

**Comment by cantlep** [comment]
Confirmed fixed. Much appreciated
