### ISSUE TITLE
Top Sender Statistics showing incorrect numbers

### ISSUE THREAD

**Issue by cantlep** [darold/sendmailanalyzer#53]
Hi,

It looks like the top senders stats (and possibly recipients, too are showing figures that are way off). For some reason, sometimes the entries in SA show a x5 or x2 next to the number of emails which makes the figures incorrect. For example. I sent you @darold 2 emails today from my personal a/c. However, when viewing the SA stats, it actually shows the first mail as x5.

![x5](https://user-images.githubusercontent.com/3270673/30454292-ba09524c-9993-11e7-9a73-8a30a6ddb8f7.png)

And as you can see from the MTA, it was only 1 mail.

![gilleslog](https://user-images.githubusercontent.com/3270673/30454369-fa51c2f8-9993-11e7-8c6c-e4a158437b6f.png)

For info, the second email I sent to you only appears as one (correctly) in the SA stats. On a side note, not sure my the magic from my log contains a contuse.com ID instead of my own domain (that only happened with that 1 email - but that's an issue for me to resolve)

This is even more apparent with recipients.

I received 37 emails today to my primary address. MTA logs confirm. SA shows 37 lines when I click the entry (correct). but actually shows a figure of 182 in the statistics and this is because every email has a x5 or a x10 next to it.

Cheers

Paul

**Comment by darold** [comment]
Got it, commit 7ea5dd7 might solve this issue. Recipient entries was duplicated when the message was also registered as Spam by spamd.

**Comment by cantlep** [comment]
Confirmed fixed. Much appreciated
