### ISSUE TITLE
How to Show Graph Information of Maillog For More One Day

### ISSUE THREAD

**Issue by ajihandoko** [darold/sendmailanalyzer#54]
I have a little question about sendmailanalyzer.

for example the information displayed in sendmailanalyzer from maillog file on Tuesday 3 October 2017, then the next day Wednesday 4 october 2017 file maillog already replace. Whether sendmailanalyzer will display the information from October 3 to 4 october or just 4 october only?

thanks darold

**Comment by darold** [comment]
SendmailAnalyzer should display all days that have been parsed from maillog provide that you don't remove data from output directory (default: /usr/local/sendmailanalyzer/data/)

**Comment by ajihandoko** [comment]
so the parsing results are stored in the directory /usr/local/sendmailanalyzer/data
ok thanks darold
