### ISSUE TITLE
How to Parse Maillog From Another Host (SMTP relay)

### ISSUE THREAD

**Issue by ajihandoko** [darold/sendmailanalyzer#55]
I have one more question.

How to parse maillog from another host (smtp server) to sendmailanalyzer ? Do I have to install certain application on my smtp server to send maillog to sendmailanalyzer ? like i have to install and start the service of snmp in my server to send syslog to cacti server.

Thanks Darold

**Comment by cantlep** [comment]
Because sendmailanalyzer utilises a web server and I didn't want to install one on my MTA, I just NFS mount the log directory from the MTA to the web server and point the sendmailanalyzer config to that directory.

**Comment by ajihandoko** [comment]
Ok cantlep, so if I want to create maillog graph of 2 server, I just add configuration LOG_FILE /dst/nfs/dir/server1 for server1 and LOG_FILE /dst/nfs/server2 for server2 in file /etc/sendmailanalyzer.conf ?

**Comment by cantlep** [comment]
I'm not entirely sure if you can parse more than one log file, the --help flag would indicate not. I only have one MTA so I don't have the same issue you have in this regard. I suppose a workaround would be a central syslog server that contains the logs for both MTAs and then reference that as one file. @darold will know if more than 1 file can be parsed in the config, I expect.

**Comment by darold** [comment]
Note that you can have multiple reports corresponding to each maillog on a single SendmailAnalyzer host. You just have to use different configuration file with different location for the following directives:
```
LOG_FILE
PID_DIR
OUT_DIR
```
Of course you must also have a dedicated sa_report CGI entry dedicated to each report.

**Comment by ajihandoko** [comment]
Sorry I'm late to response your answer. 
Oke darold, I will try to my server.
Thanks darold, for your reply.

**Comment by ajihandoko** [comment]
hai darold, 
I have fix this issue with merge maillog-of-smtp1 and maillog-of-smtp2 to be one file "maillog".
