### ISSUE TITLE
Debian 9 - no report, just header

### ISSUE THREAD

**Issue by a-ttila** [darold/sendmailanalyzer#56]
On my Debian Stretch box, I have the header of the report only. Even the first two menu points - Global statistics and Top statistics - are missing, there are only empty 'li' HTML elements.
I have Postfix installed.
It worked while I used Debian Jessie.
Would you help me, please?
THX,
Attila

**Comment by darold** [comment]
Please post a screenshot, I don't see what you are reporting.

**Comment by a-ttila** [comment]
https://pasteboard.co/GO9JuyQ.png

**Comment by darold** [comment]
OK, I understand know. Please use latest code from github commit b008420 fix this issue.

**Comment by a-ttila** [comment]
Ah, it works now! Thank you very much! You do an awesome work with this project. ;-)
