### ISSUE TITLE
Databases (*.dat) are started with correct time, but are not ended with correct one.

### ISSUE THREAD

**Issue by enekux** [darold/sendmailanalyzer#57]
Hi,

when checking the .dat files I see the next:

head -n1 data/goban/2017/11/30/senders.dat 
000001:870121789C:.....@.....com:12895:1:localhost:

tail -n1 data/goban/2017/11/30/senders.dat 
075750:46F6F17F00:...@...:4598:1::

I believe that all "*.dat" files would have to end at 235959...

So I believe that the results in the statistics show wrong data...

**Comment by darold** [comment]
Sorry for the response delay.

Obviously here it seems that the last message processed by sendmailanalyzer was at 2017-11-30 07:57:50. If you received other messages later, they will be appended to the dat file. If this is not the case this is because sendmailanalyzer was stopped.
