### ISSUE TITLE
no statistics are shown for Postgrey (sqlgrey)

### ISSUE THREAD

**Issue by enekux** [darold/sendmailanalyzer#60]
Hi,
I have recently noticed that there are no statistics shown for Postgrey. In our case we are using sqlgrey. We have this parameter in our configuration file:

POSTGREY_NAME   postgrey|sqlgrey

Any ideas?

Thank you

**Comment by darold** [comment]
Hi,

Please send me a log otherwise I will not be able to investigate what's going wrong.

Best regards,

**Comment by enekux** [comment]
Jun  6 09:31:35 servername sqlgrey: grey: domain awl match: updating x.x.x.x(x.x.x.x), domain.com
Jun  6 09:31:35 servername sqlgrey: grey: domain awl match: updating x.x.x.x(x.x.x.x), domain.com

**Comment by darold** [comment]
I don't know what to report with that, can you send me a real log to my private email gilles@darold.net ?

**Comment by darold** [comment]
Fixed.
