### ISSUE TITLE
Wrong numbers shown at Top Statistics / Spamming / Top Spams Rules for "DNSBL Spam blocked" and "Amavis Passed Spam"

### ISSUE THREAD

**Issue by enekux** [darold/sendmailanalyzer#62]
Hi,
I have noticed that a wrong number is shown at Top Statistics / Spamming / Top Spams Rules / DNSBL Spam blocked.

$ cat spam.dat | grep "DNSBL Spam blocked" | sort | wc -l
14408

and instead it shows "DNSBL Spam blocked (7158)"

And the same happens with "Amavis Passed Spam"

$ cat spam.dat | grep "Amavis Passed Spam" | sort | wc -l
2194

and instead, it shows "Amavis Passed Spam (945)"

I think that the other results also need to be checked like: "Top Spammers Domain", "Top Spammers Relays", ....

Thank you,

**Comment by darold** [comment]
I'm not able to reproduce the problem even with your previous log. Can you send me the log from the spam.dat file you are querying?

**Comment by enekux** [comment]
Sorry once again, I checked something wrong. The results are correct.
Thank you and regards,
