### ISSUE TITLE
Top statistic , spam detail no sender relay

### ISSUE THREAD

**Issue by biji** [darold/sendmailanalyzer#68]
Top statistic  - spamming - click to open  detail , also does not show sender relay

For example: http://mail.abcd.com/sa/sa_report.cgi?host=mail&date=20190205&hour=&type=spam&peri=rule&domain=&search=Amavis%20Discarded%20spam

Maybe related to: https://github.com/darold/sendmailanalyzer/pull/67

**Comment by darold** [comment]
Thanks for the report, commit 6ba9d84 solves this issue.

**Comment by biji** [comment]
Great.. it works
