### ISSUE TITLE
 It does not show the graphs

### ISSUE THREAD

**Issue by tleguizamon** [darold/sendmailanalyzer#71]
Good morning!

The application is not showing the graphs, even if it is active in the configuration.

Attached capture, to see if you can help me.

From already thank you very much.

Greetings.

![Sendmailanalizer](https://user-images.githubusercontent.com/59257000/71479121-eb723500-27d1-11ea-87bc-f587d4cec5a5.png)

**Comment by darold** [comment]
Hi,

I guess that you have not installed SendmailAnalyzer correctly or something has changed since the first install. As you can see the logo is not displayed too that mean that the CGI can't find the logo and resources files where they are expected:
```
<script type="text/javascript" src="flotr2.js"></script>
<script type="text/javascript" src="sorttable.js"></script>
<img src="salogo.png" border="0" ...>
```
Listing of the default installation path must show the following files:
```
$ ls /usr/local/sendmailanalyzer/www/
flotr2.js  lang/  salogo.png  sa_report.cgi  sorttable.js
```
If you have installed resources files elsewhere you must set the URL in the sendmailanalyzer.conf file:
```
# Path to the Sendmail.org logo. Default current directory
URL_LOGO        salogo.png

# Path to the flotr2 javascript library. Default current directory
URL_JSCRIPT     flotr2.js

# Path to the sortable javascript library. Default current directory
URL_SORTABLE    sorttable.js
```

Regards,

**Comment by tleguizamon** [comment]
Thank you very much for the reply.

The application was installed in another directory, since the hosting where I have it requires it.

I was in charge of modifying the paths where the indicated files are located (flotr2.js, sorttable.js and salogo.png) in "sendmailanalyzer.conf" but still does not graph or show the logo.

On the other hand, if I modify for example: VIRUS_VIEW <----> 0 removes it from the application.

**Comment by darold** [comment]
Look at the Apache error log to see what's going wrong with the url path for the resource file.

Disabling VIRUS_VIEW remove the link to see virus statistics, so related reports might not appear.

**Comment by tleguizamon** [comment]
Good morning Darold, nice to greet you.

I have installed Sendmailanalizer again, but I can't make it graph or even show the logo.

I would like to know if it is necessary to add any directive in the CGI-BIN for this to work.


Currently in the apache log I see no errors and the routes are well declared in the configuration file "/usr/local/sendmailanalyzer/sendmailanalyzer.conf".

**Comment by darold** [comment]
Hi,

Have a look to URL_LOGO and URL_JSCRIPT in sendmailanalyzer.conf, may be you have to prefix a path to the current value so that they can be loaded by the Web page.

**Comment by tleguizamon** [comment]
Dear.
Check the paths of the sendmailanalyzer.conf file and they are correct.

The error only appears in the graphics and in the logo.

![sendmail](https://user-images.githubusercontent.com/59257000/75037150-43f04680-5492-11ea-9d71-000c35fdb65e.png)

**Comment by darold** [comment]
If you have the following in your sendmailanalyzer.conf
```
# Path to the Sendmail.org logo. Default current directory
URL_LOGO        salogo.png

# Path to the flotr2 javascript library. Default current directory
URL_JSCRIPT     flotr2.js
```
you will see in the sources of the HTLM page generated by the CGI :
```
<script type="text/javascript" src="flotr2.js"></script>
<script type="text/javascript" src="sorttable.js"></script>
```

Click on the filename (sorttable.js for example) and you should see the content of this javascript file. If not the path do not correspond to the right place where these files can be found or they are not present. If they are not present you can copy them from source tree.

**Comment by tleguizamon** [comment]
Darold

When doing the indicated with both files (flotr2.js and sorttable.js) I receive the following error:

Not Found
The requested URL /var/www/analizer/public_html/cgi-bin/sorttable.js was not found on this server.

Not Found
The requested URL /var/www/analizer/public_html/cgi-bin/flotr2.js was not found on this server.

In the apache log, you don't log anything, if the routes are not correct, you should see it there.

On the other hand, I am struck that the report is done correctly, only what does not work are the graphics.

**Comment by darold** [comment]
What is the full path to the CGI script sa_report.cgi on your system?

**Comment by tleguizamon** [comment]
Darold.

I currently have the "sa_report.cgi" in the following route "/var/www/analizer/public_html/cgi-bin/sa_report.cgi".

**Comment by darold** [comment]
then copy flotr2.js, sorttable.js  and salogo.png from the SendamAnalyzer sources to directory /var/www/analizer/public_html/cgi-bin/

**Comment by tleguizamon** [comment]
Darold

I already did what you mentioned.
It was one of the first things I did.

![sendmail](https://user-images.githubusercontent.com/59257000/75052802-f0402600-54ae-11ea-9ba4-472d6d473e0d.png)

**Comment by darold** [comment]
Can you post your apache configuration related to SA?

**Comment by tleguizamon** [comment]
Yes of course.

I have configured a Vhost, as follows:

[root@vps-1419828-x ~] # cat /etc/httpd/sites-available/analizer.tk.conf 
<VirtualHost *:80>
ServerAdmin tomas.leguizamon@donweb.com
ServerName www.analizer.tk
ServerAlias analizer.tk
AddHandler cgi-script .pl .cgi
DocumentRoot /var/www/analizer/public_html
ErrorLog /var/www/analizer/error.log
CustomLog /var/www/analizer/access.log combined

ScriptAlias "/cgi-bin/" "/var/www/analizer/public_html/cgi-bin/"

</Virtualhost>

**Comment by darold** [comment]
Perhaps you should move flotr2.js, sorttable.js and salogo.png to /var/www/analizer/public_html and set:
```
# Path to the Sendmail.org logo. Default current directory
URL_LOGO        /salogo.png

# Path to the flotr2 javascript library. Default current directory
URL_JSCRIPT     /flotr2.js

# Path to the sortable javascript library. Default current directory
URL_SORTABLE    /sorttable.js
```

**Comment by tleguizamon** [comment]
Darold


Now it works.

Thank you very much for the help.

Best regards.
