### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by mindrunner** [darold/sendmailanalyzer#72]
Hey there! Nice Project. I am using docker-mailserver and currently building a standalone out of the box running docker image for sendmailanalyzer. Still experimental and not everything is working I suppose (need hooks for logrotation for example).

See here: https://github.com/tomav/docker-mailserver/issues/1385

Is there any interest in integrating this here upstream and having an official image? Or shall I rather create this as a separate project?

**Comment by mindrunner** [comment]
pretty dead project, huh?

**Comment by darold** [comment]
Hi,

Sorry for my silent, I totally forgot to answer to your issue. If you have a docker file please submit a pull request I will be please to add it. Let me know if you have any question.

Best regards,

**Comment by mindrunner** [comment]
Filed PR

**Comment by darold** [comment]
Applied, thanks a lot.
