### ISSUE TITLE
Week Numbers in the first 9 Weeks of Year

### ISSUE THREAD

**Issue by jassi0001** [darold/sendmailanalyzer#73]
Hi, i have the problem, that the sarport Websites shows not the correct Week-Number, in the url-Line, when i click on the week on the website.

The weeks shown up as "01", 02", "03", etc. When i click, the url is only shown as "1","2","3", etc...
https://mailurl.dot.de/sareport/sa_report.cgi?host=hostname&date=20190127&week=3

The Cache Folder is created with  "01", 02", "03", too.

Maybe you can fix this in the next version

**Comment by darold** [comment]
Might be fixed by commit 45b5e31
