### ISSUE TITLE
Add support for Anti-Spam SMTP Proxy Server (ASSP) logs

### ISSUE THREAD

**Issue by ravensorb** [darold/sendmailanalyzer#77]
Any thought to adding in support for ASSP (https://sourceforge.net/projects/assp/) log files?

**Comment by darold** [comment]
If you can provide me a sample log file I will see if this is feasible.

**Comment by ravensorb** [comment]
Happy to -- Are you ok if I send it via email?

**Comment by darold** [comment]
yes no pb

**Comment by darold** [comment]
Won't be done, ASSP has his own log format that is not compatible or at least it will need a huge work to support it.
